### ISSUE TITLE
Misc to-do for our version

### ISSUE THREAD

**Issue by rkdarst** [CxAalto/aware-client#1]
This contains various small or easy things.  More things will be added directly to here as needed.
- [x] Remove AWARE stream from home screen
- [x] Remove Oulu server ping
- [x] Change app user-visible name
